# Generated by Django 5.0 on 2023-12-23 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('secondname', models.CharField(max_length=200)),
                ('patronymic', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('checking_account', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('opened', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('secondname', models.CharField(max_length=200)),
                ('patronymic', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Ring', 'Ring'), ('Brooch', 'Brooch'), ('Bracelet', 'Bracelet'), ('Anklet', 'Anklet'), ('Necklace', 'Necklace'), ('Earring', 'Earring'), ('Cuff links', 'Cuff links'), ('Locket', 'Locket'), ('Pendant', 'Pendant')], max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('defects', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tableManager.client')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tableManager.store')),
            ],
        ),
    ]
