# Generated by Django 5.0 on 2023-12-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableManager', '0002_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
